services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
